# Generated by Django 4.0 on 2022-01-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
