# Generated by Django 4.0 on 2022-01-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postmodel_likes_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
